function y = refilterCSCdata(x)
%FIR_FILTER Filters input x and returns output y.

% MATLAB Code
% Generated by MATLAB(R) 8.6 and the Signal Processing Toolbox 7.1.
% Generated on: 21-Nov-2015 21:02:21

persistent Hd;

if isempty(Hd)
    
    Fstop1 = 290;    % First Stopband Frequency
    Fpass1 = 300;    % First Passband Frequency
    Fpass2 = 6000;   % Second Passband Frequency
    Fstop2 = 6100;   % Second Stopband Frequency
    Astop1 = 60;     % First Stopband Attenuation (dB)
    Apass  = 1;      % Passband Ripple (dB)
    Astop2 = 60;     % Second Stopband Attenuation (dB)
    Fs     = 32000;  % Sampling Frequency
    
    h = fdesign.bandpass('fst1,fp1,fp2,fst2,ast1,ap,ast2', Fstop1, Fpass1, ...
        Fpass2, Fstop2, Astop1, Apass, Astop2, Fs);
    
    Hd = design(h, 'equiripple', ...
        'MinOrder', 'any');
    
    
    
    set(Hd,'PersistentMemory',true);
    
end

y = filtfilt(Hd.Numerator,1,x);


