function y = refilterCSCdata_v3_IIR(x)
%REFILTERCSCDATA_V3_IIR Filters input x and returns output y.

% MATLAB Code
% Generated by MATLAB(R) 8.6 and the DSP System Toolbox 9.1.
% Generated on: 25-Mar-2016 12:33:46

persistent Hd;

if isempty(Hd)
    
    Fstop1 = 290;    % First Stopband Frequency
    Fpass1 = 300;    % First Passband Frequency
    Fpass2 = 6000;   % Second Passband Frequency
    Fstop2 = 6100;   % Second Stopband Frequency
    Astop1 = 60;     % First Stopband Attenuation (dB)
    Apass  = 1;      % Passband Ripple (dB)
    Astop2 = 60;     % Second Stopband Attenuation (dB)
    Fs     = 32000;  % Sampling Frequency
    
    h = fdesign.bandpass('fst1,fp1,fp2,fst2,ast1,ap,ast2', Fstop1, Fpass1, ...
        Fpass2, Fstop2, Astop1, Apass, Astop2, Fs);
    
    Hd = design(h, 'butter', ...
        'MatchExactly', 'passband', ...
        'SOSScaleNorm', 'Linf');
    
    
    
    set(Hd,'PersistentMemory',true);
    
end

y = filter(Hd,x);


