function [fitresult, gof] = singleExpFitInt(x,y,plotFlag)
%CREATEFIT(X,Y)
%  Create a fit.
%
%  Data for 'singleExpFitInt' fit:
%      Y Output: y
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 26-Jul-2017 13:15:14

if nargin < 3
    plotFlag = 0;
end

%% Fit: 'singleExpFitInt'.
[xData, yData] = prepareCurveData( x, y );

% Set up fittype and options.
ft = fittype( 'a*exp(-b*x)+c', 'independent', 'x', 'dependent', 'y' );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Display = 'Off';
opts.StartPoint = [0.804177007862855 0.00456337817014296 0.519120889538168];

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );

if plotFlag == 1
    % Plot fit with data.
    figure( 'Name', 'singleExpFitInt' );
    h = plot( fitresult, xData, yData );
    legend( h, 'fortyAvg vs. x', 'singleExpFitInt', 'Location', 'NorthEast' );
    % Label axes
    xlabel x
    ylabel y
    grid on
end

